# Generated by Django 2.2.3 on 2019-07-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
