# Generated by Django 2.2.3 on 2019-07-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0003_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
