# Generated by Django 2.2.3 on 2019-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0004_auto_20190724_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dis',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub',
            field=models.CharField(max_length=2000),
        ),
    ]
