# Generated by Django 2.2.3 on 2019-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0006_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=5000)),
                ('InvoiceNumber', models.CharField(max_length=5000)),
                ('ProductName', models.CharField(max_length=5000)),
                ('ProductId', models.CharField(max_length=5000)),
                ('Quality', models.IntegerField(max_length=5000)),
                ('Price', models.CharField(max_length=5000)),
                ('Size', models.CharField(max_length=5000)),
                ('UserFullName', models.CharField(max_length=5000)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNumber', models.IntegerField(max_length=10)),
                ('Address', models.IntegerField(max_length=5000)),
                ('ShippingUserName', models.CharField(max_length=5000)),
                ('ShippingUserContactNumber', models.IntegerField(max_length=10)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('ZipCode', models.IntegerField(max_length=40)),
                ('ClientGst', models.CharField(max_length=2000)),
                ('ModOfPayment', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('ShippingCost', models.IntegerField(verbose_name=2000)),
            ],
        ),
    ]
