# Generated by Django 2.2.3 on 2019-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0008_auto_20190805_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Address',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='Quality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ShippingUserContactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ZipCode',
            field=models.IntegerField(),
        ),
    ]
