# Generated by Django 2.2.3 on 2019-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0009_auto_20190805_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='ContactNumber',
            field=models.IntegerField(),
        ),
    ]
