# Generated by Django 2.2.3 on 2019-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0010_auto_20190805_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Address',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ContactNumber',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='Quality',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ShippingCost',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ShippingUserContactNumber',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ZipCode',
            field=models.CharField(max_length=5000),
        ),
    ]
