# Generated by Django 2.2.3 on 2019-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0011_auto_20190806_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Size',
            field=models.CharField(choices=[('select', 'Select'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='select', max_length=6),
        ),
    ]
