# Generated by Django 2.2.3 on 2019-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0012_auto_20190806_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='Addition',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='Division',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
