# Generated by Django 2.2.3 on 2019-08-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0013_auto_20190807_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='Addition',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='Division',
        ),
    ]
