# Generated by Django 2.2.3 on 2019-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0014_auto_20190808_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='Quality',
            new_name='Quantity',
        ),
    ]
