# Generated by Django 2.2.3 on 2019-08-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0015_auto_20190808_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='Quantity',
            new_name='Quality',
        ),
    ]
