# Generated by Django 2.2.3 on 2019-08-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0016_auto_20190808_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceModel',
            new_name='MakeInvoiceModel',
        ),
    ]
